from turtle import Turtle, Screen

tim = Turtle()

tim.shape('turtle')
tim.penup()
# timmy_the_turtle.hideturtle()
tim.speed('slow')
tim.left(90)
tim.forward(50)
tim.right(90)
tim.pendown()
tim.forward(50)
tim.right(90)
tim.forward(100)
tim.right(90)
tim.forward(100)
tim.right(90)
tim.forward(100)
tim.right(90)
tim.forward(50)
tim.penup()
tim.right(90)
tim.forward(50)
tim.left(90)
# timmy_the_turtle.showturtle()

screen = Screen()
screen.exitonclick()
